-- TABELAS FORTES:

-- ARMAZENA A CONTA DO USUARIO
DROP TABLE IF EXISTS T_SC_USERS;

CREATE TABLE IF NOT EXISTS T_SC_USERS(
	ID SERIAL PRIMARY KEY,
	NM_USER VARCHAR(200) NOT NULL,
	DS_EMAIL TEXT UNIQUE NOT NULL,
	PS_PASSWORD	TEXT NOT NULL,
	DT_CREATION TIMESTAMP DEFAULT NOW()
);


-- ARMAZENA TODOS OS TITULOS
DROP TABLE IF EXISTS T_SC_MOVIES;

CREATE TABLE IF NOT EXISTS T_SC_MOVIES(
	ID SERIAL PRIMARY KEY,
	NM_MOVIE VARCHAR(200) NOT NULL,
	DT_RELEASE TIMESTAMP,
	DS_CLASSIFICATION VARCHAR(5),
	TM_DURATION INTEGER,
	DS_MOVIE TEXT,
	NM_IMAGE VARCHAR(120),
	DT_INSERT TIMESTAMP NOT NULL DEFAULT NOW(),
	DT_UPDATE TIMESTAMP
);

-- ARMAZENA TODAS AS CATEGORIAS QUE O FILME POSSUI
DROP TABLE IF EXISTS T_SC_CATEGORIES;

CREATE TABLE IF NOT EXISTS T_SC_CATEGORIES(
	ID SERIAL PRIMARY KEY,
	NM_CATEGORIE VARCHAR(200) NOT NULL,
	DT_INSERT TIMESTAMP NOT NULL DEFAULT NOW()
);

-- TABELAS ASSOCIATIVAS
DROP TABLE IF EXISTS T_SC_MOVIE_CATEGORIES;

CREATE TABLE IF NOT EXISTS T_SC_MOVIE_CATEGORIES(
	ID SERIAL PRIMARY KEY,
	ID_MOVIE INTEGER NOT NULL,
	ID_CATEGORIE INTEGER NOT NULL,
	ST_CATEGORIE_DEFAULT BOOLEAN DEFAULT 'false',
	DT_INSERT TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE T_SC_MOVIE_CATEGORIES ADD CONSTRAINT FK_MOVIE_CATEGORIES_MOVIE FOREIGN KEY (ID_MOVIE) REFERENCES T_SC_MOVIES(ID);
ALTER TABLE T_SC_MOVIE_CATEGORIES ADD CONSTRAINT FK_MOVIE_CATEGORIES_CATEGORIE FOREIGN KEY (ID_CATEGORIE) REFERENCES T_SC_CATEGORIES(ID);




DROP TABLE IF EXISTS T_SC_WATCHED_MOVIES;

CREATE TABLE IF NOT EXISTS T_SC_WATCHED_MOVIES(
	ID SERIAL PRIMARY KEY,
	ID_MOVIE INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	DT_WATCHED TIMESTAMP NOT NULL,
	TX_EVALUATION TEXT NOT NULL,
	NR_SCORE INTEGER NOT NULL
);

ALTER TABLE T_SC_WATCHED_MOVIES ADD CONSTRAINT FK_WATCHED_MOVIES_MOVIE FOREIGN KEY (ID_MOVIE) REFERENCES T_SC_MOVIES(ID);
ALTER TABLE T_SC_WATCHED_MOVIES ADD CONSTRAINT FK_WATCHED_MOVIES_USER FOREIGN KEY (ID_USER) REFERENCES T_SC_USERS(ID);



